services:
  - type: web
    name: cnaps-interface
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: data
      mountPath: /mnt/data
      sizeGB: 1
